version: '3.8'

services:
bot:
build: .
ports:
- "8080:8080"
environment:
- BOT_TOKEN=${BOT_TOKEN}
- DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
volumes:
- .:/app
depends_on:
- db

db:
image: postgres:latest
environment:
POSTGRES_USER: myuser
POSTGRES_PASSWORD: mypassword
POSTGRES_DB: mydb
volumes:
- db_data:/var/lib/postgresql/data

volumes:
db_data:
